# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master
- release

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.Full.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  mdixColorsVersion: '2.0.0'
  mdixMahAppsVersion: '0.1.6'
  mdixVersion: '4.0.0'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Restore tools'
  inputs:
    command: custom 
    custom: tool
    arguments: restore

- task: DotNetCoreCLI@2
  displayName: 'Restore via paket'
  inputs:
    command: custom 
    custom: paket 
    arguments: restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU" /p:MDIXVersion=$(mdixVersion).$(Build.BuildID) /p:MDIXColorsVersion=$(mdixColorsVersion).$(Build.BuildID) /p:MDIXMahAppsVersion=$(mdixMahappsVersion).$(Build.BuildID)'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'UI Tests'
  inputs:
    command: test
    projects: '**/*.UITests'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: PublishPipelineArtifact@0
  name: "PublishUITestsScreenshots"
  inputs:
    artifactName: 'Screenshots'
    targetPath: 'MaterialDesignThemes.UITests/bin/$(buildConfiguration)/netcoreapp3.1/Screenshots'
  condition: always()

- task: PowerShell@2
  displayName: "Build NuGets"
  inputs: 
    filePath: 'Scripts\\BuildNugets.ps1'
    arguments: '-MDIXVersion $(mdixVersion)-ci$(Build.BuildId) -MDIXMahAppsVersion $(mdixMahappsVersion)-ci$(Build.BuildId) -MDIXColorsVersion $(mdixColorsVersion)-ci$(Build.BuildId)'

- task: PublishPipelineArtifact@0
  name: "PublishDemoApp"
  inputs:
    artifactName: 'DemoApp'
    targetPath: 'MainDemo.Wpf/bin/$(buildConfiguration)'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesign"
  inputs:
    artifactName: 'MDIX'
    targetPath: 'MaterialDesignThemes.$(mdixVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignColors"
  inputs:
    artifactName: 'MDIX.Colors'
    targetPath: 'MaterialDesignColors.$(mdixColorsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignMahApps"
  inputs:
    artifactName: 'MDIX.MahApps'
    targetPath: 'MaterialDesignThemes.MahApps.$(mdixMahappsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishScript"
  inputs:
    artifactName: 'Script'
    targetPath: 'Scripts\\UpdateNugets.ps1'